### ISSUE TITLE
Encountered exception during recovery

### ISSUE THREAD

**Issue by vladikk007** [Mordred/certbot-plugin-websupport#1]
Hello,

I tried to generate cert, however en error occured:

`[vladikk@oasybri websupport]$ sudo certbot certonly -a certbot-plugin-websupport:dns --certbot-plugin-websupport:dns-credentials websupport.ini -d oasybri.autocar.sk

Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator certbot-plugin-websupport:dns, Installer None
Obtaining a new certificate
Performing the following challenges:
dns-01 challenge for oasybri.autocar.sk
Cleaning up challenges
Encountered exception during recovery:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/certbot/_internal/auth_handler.py", line 70, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/usr/lib/python3.6/site-packages/certbot/plugins/dns_common.py", line 57, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/usr/local/lib/python3.6/site-packages/certbot_plugin_websupport/dns.py", line 57, in _perform
    self._get_websupport_client().add_txt_record(domain, validation_name, validation, self.ttl)
  File "/usr/local/lib/python3.6/site-packages/certbot_plugin_websupport/dns.py", line 87, in add_txt_record
    zone_id = self._find_zone_id(domain)
  File "/usr/local/lib/python3.6/site-packages/certbot_plugin_websupport/dns.py", line 159, in _find_zone_id
    response = self._send_request('GET', '/v1/user/self/zone/{0}'.format(zone_id))
  File "/usr/local/lib/python3.6/site-packages/certbot_plugin_websupport/dns.py", line 202, in _send_request
    signature = hmac.new(self.api_secret, canonical_request.encode('utf-8'), hashlib.sha1).hexdigest()
  File "/usr/lib64/python3.6/hmac.py", line 185, in new
    return HMAC(key, msg, digestmod)
  File "/usr/lib64/python3.6/hmac.py", line 49, in __init__
    raise TypeError("key: expected bytes or bytearray, but got %r" % type(key).__name__)
TypeError: key: expected bytes or bytearray, but got 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/certbot/_internal/error_handler.py", line 125, in _call_registered
    self.funcs[-1]()
  File "/usr/lib/python3.6/site-packages/certbot/_internal/auth_handler.py", line 243, in _cleanup_challenges
    self.auth.cleanup(achalls)
  File "/usr/lib/python3.6/site-packages/certbot/plugins/dns_common.py", line 76, in cleanup
    self._cleanup(domain, validation_domain_name, validation)
  File "/usr/local/lib/python3.6/site-packages/certbot_plugin_websupport/dns.py", line 60, in _cleanup
    self._get_websupport_client().del_txt_record(domain, validation_name, validation)
  File "/usr/local/lib/python3.6/site-packages/certbot_plugin_websupport/dns.py", line 126, in del_txt_record
    zone_id = self._find_zone_id(domain)
  File "/usr/local/lib/python3.6/site-packages/certbot_plugin_websupport/dns.py", line 159, in _find_zone_id
    response = self._send_request('GET', '/v1/user/self/zone/{0}'.format(zone_id))
  File "/usr/local/lib/python3.6/site-packages/certbot_plugin_websupport/dns.py", line 202, in _send_request
    signature = hmac.new(self.api_secret, canonical_request.encode('utf-8'), hashlib.sha1).hexdigest()
  File "/usr/lib64/python3.6/hmac.py", line 185, in new
    return HMAC(key, msg, digestmod)
  File "/usr/lib64/python3.6/hmac.py", line 49, in __init__
    raise TypeError("key: expected bytes or bytearray, but got %r" % type(key).__name__)
TypeError: key: expected bytes or bytearray, but got 'str'
An unexpected error occurred:
TypeError: key: expected bytes or bytearray, but got 'str'
Please see the logfiles in /var/log/letsencrypt for more details.
`
Could you please help me? 
Thanks

**Comment by Mordred** [comment]
Hi, can you test v0.1.4 (e5d776388d366caa77b3dde431554e8bd2dd5992)?

**Comment by vladikk007** [comment]
Thanks for your support...
output is the same:
Encountered exception during recovery:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/certbot/_internal/auth_handler.py", line 70, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/usr/lib/python3.6/site-packages/certbot/plugins/dns_common.py", line 57, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/usr/local/lib/python3.6/site-packages/certbot_plugin_websupport/dns.py", line 57, in _perform
    self._get_websupport_client().add_txt_record(domain, validation_name, validation, self.ttl)
  File "/usr/local/lib/python3.6/site-packages/certbot_plugin_websupport/dns.py", line 87, in add_txt_record
    zone_id = self._find_zone_id(domain)
  File "/usr/local/lib/python3.6/site-packages/certbot_plugin_websupport/dns.py", line 159, in _find_zone_id
    response = self._send_request('GET', '/v1/user/self/zone/{0}'.format(zone_id))
  File "/usr/local/lib/python3.6/site-packages/certbot_plugin_websupport/dns.py", line 205, in _send_request
    "Authorization": "Basic %s" % (base64.b64encode("%s:%s" % (self.api_key, signature))),
  File "/usr/lib64/python3.6/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

**Comment by vladikk007** [comment]
I tried to use pip2 to install plugin and it works now. (before i've used pip3)

**Comment by Mordred** [comment]
OK, I've added more encode/decode 59d3e48219b4d799d89e43402b0b8b8577476537 try v0.1.5
