### ISSUE TITLE
All renewal attempts failed

### ISSUE THREAD

**Issue by vladikk007** [Mordred/certbot-plugin-websupport#3]
Your plugin works great, however it stopped renew my cert. Could you please help me?

2021-02-24 06:45:59,445:ERROR:certbot._internal.error_handler:Encountered exception during recovery: TypeError: a bytes-like object is required, not 'str'
2021-02-24 06:45:59,446:WARNING:certbot._internal.renewal:Attempting to renew cert (domain.sk) from /etc/letsencrypt/renewal/domain.sk.conf produced an unexpected error: a bytes-like object is required, not 'str'. Skipping.
2021-02-24 06:45:59,447:DEBUG:certbot._internal.renewal:Traceback was:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/certbot/_internal/renewal.py", line 472, in handle_renewal_request
    main.renew_cert(lineage_config, plugins, renewal_candidate)
  File "/usr/lib/python3.6/site-packages/certbot/_internal/main.py", line 1234, in renew_cert
    renewed_lineage = _get_and_save_cert(le_client, config, lineage=lineage)
  File "/usr/lib/python3.6/site-packages/certbot/_internal/main.py", line 123, in _get_and_save_cert
    renewal.renew_cert(config, domains, le_client, lineage)
  File "/usr/lib/python3.6/site-packages/certbot/_internal/renewal.py", line 330, in renew_cert
    new_cert, new_chain, new_key, _ = le_client.obtain_certificate(domains, new_key)
  File "/usr/lib/python3.6/site-packages/certbot/_internal/client.py", line 374, in obtain_certificate
    orderr = self._get_order_and_authorizations(csr.data, self.config.allow_subset_of_names)
  File "/usr/lib/python3.6/site-packages/certbot/_internal/client.py", line 421, in _get_order_and_authorizations
    authzr = self.auth_handler.handle_authorizations(orderr, best_effort)
  File "/usr/lib/python3.6/site-packages/certbot/_internal/auth_handler.py", line 70, in handle_authorizations
    resps = self.auth.perform(achalls)
  File "/usr/lib/python3.6/site-packages/certbot/plugins/dns_common.py", line 57, in perform
    self._perform(domain, validation_domain_name, validation)
  File "/usr/local/lib/python3.6/site-packages/certbot_plugin_websupport/dns.py", line 57, in _perform
    self._get_websupport_client().add_txt_record(domain, validation_name, validation, self.ttl)
  File "/usr/local/lib/python3.6/site-packages/certbot_plugin_websupport/dns.py", line 87, in add_txt_record
    zone_id = self._find_zone_id(domain)
  File "/usr/local/lib/python3.6/site-packages/certbot_plugin_websupport/dns.py", line 159, in _find_zone_id
    response = self._send_request('GET', '/v1/user/self/zone/{0}'.format(zone_id))
  File "/usr/local/lib/python3.6/site-packages/certbot_plugin_websupport/dns.py", line 205, in _send_request
    "Authorization": "Basic %s" % (base64.b64encode("%s:%s" % (self.api_key, signature))),
  File "/usr/lib64/python3.6/base64.py", line 58, in b64encode
    encoded = binascii.b2a_base64(s, newline=False)
TypeError: a bytes-like object is required, not 'str'

Thanks

**Comment by Mordred** [comment]
This should be fixed in v0.1.5  .. did you tried it?

**Comment by vladikk007** [comment]
I've tried it again and it works now. Thanks
